trigger:
  branches:
    include:
    - master
    - develop
  
stages:
- stage: build
  pool:
    vmImage: 'ubuntu-latest'
  displayName: Build & Test
  condition: always()
  jobs:
  - job: build_front
    condition: always()
    displayName: Build Triton
    steps:
    - checkout: self
    - task: Npm@1
      name: npm_install
      displayName: Install Dependencies
      condition: always()
      inputs:
        command: install
    - task: Npm@1
      name: npm_build
      displayName: Build Triton
      inputs:
        command: custom
        customCommand: run build:ci
    - task: PublishPipelineArtifact@1
      name: publish_build
      displayName: Publish dist folder
      condition: always()
      inputs:
        artifact: triton
        publishLocation: pipeline
        targetPath: dist
    - task: PublishPipelineArtifact@1
      name: publish_build_conf
      displayName: Publish NGINX Conf
      condition: always()
      inputs:
        artifact: nginx
        publishLocation: pipeline
        targetPath: nginx.conf

- stage: deploy_dev
  displayName: Deploy DEV
  variables:
  - name: workDir
    value: $(app.location)
  - name: nginx_conf
    value: /etc/nginx/sites-available/triton
  - group: triton_dev
  jobs:
  - template: deployment_onprem.template.yml
    parameters:
      deploymentName: deploy_fe_dev
      deploymentDisplayName: Deploy Triton DEV
      env: DEV
      tags: azurevm
      workingDirectory: $(workDir)
      nginxConf: $(nginx_conf)
      
- stage: deploy_qa
  displayName: Deploy QA
  variables:
  - name: workDir
    value: $(app.location)
  - name: nginx_conf
    value: /etc/nginx/sites-available/triton
  - group: triton_qa
  jobs:
  - template: deployment_onprem.template.yml
    parameters:
      deploymentName: deploy_fe_qa
      deploymentDisplayName: Deploy Triton QA
      env: QA
      tags: azurevm
      workingDirectory: $(workDir)
      nginxConf: $(nginx_conf)
      
- stage: deploy_prod
  displayName: Deploy PROD
  variables:
  - name: workDir
    value: $(app.location)
  - name: nginx_conf
    value: /etc/nginx/sites-available/triton
  - group: triton_qa
  jobs:
  - template: deployment_onprem.template.yml
    parameters:
      deploymentName: deploy_fe_prod
      deploymentDisplayName: Deploy Triton PROD
      env: PROD
      tags: azurevm
      workingDirectory: $(workDir)
      nginxConf: $(nginx_conf)